
package projctmad;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.awt.event.*;
import java.io.File;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;
import java.io.FileInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
public class signup2 extends javax.swing.JFrame {

    
    
    /**
     * Creates new form f
     */
    public signup2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        show = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        Signin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Man = new javax.swing.JRadioButton();
        Woman = new javax.swing.JRadioButton();
        user = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        edit = new javax.swing.JButton();
        Profile = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(0, 153, 51));
        show.setToolTipText("show password");
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye-crossed (1).png"))); // NOI18N
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, 20));

        jLabel4.setText("Do you have an account?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 140, -1));

        Signin.setBackground(new java.awt.Color(51, 51, 51));
        Signin.setText("Sign in");
        Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninActionPerformed(evt);
            }
        });
        getContentPane().add(Signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lll.png"))); // NOI18N
        jLabel2.setText("user");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 80, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-envelope.png"))); // NOI18N
        jLabel3.setText("email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 80, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock.png"))); // NOI18N
        jLabel5.setText("password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 80, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-phone-flip.png"))); // NOI18N
        jLabel6.setText("phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 80, -1));

        buttonGroup1.add(Man);
        Man.setText("Man");
        Man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bussiness-man.png"))); // NOI18N
        Man.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ManItemStateChanged(evt);
            }
        });
        Man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManActionPerformed(evt);
            }
        });
        getContentPane().add(Man, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 50, -1));

        buttonGroup1.add(Woman);
        Woman.setText("Woman");
        Woman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/woman.png"))); // NOI18N
        Woman.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WomanItemStateChanged(evt);
            }
        });
        getContentPane().add(Woman, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, 20));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 110, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sexual.png"))); // NOI18N
        jLabel7.setText("gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 60, 20));

        combo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combo1.setForeground(new java.awt.Color(0, 102, 102));
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Moderators" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 20));

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gallery.png"))); // NOI18N
        edit.setToolTipText("Insert a picture");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 20, 20));

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 70, 70));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id-card.png"))); // NOI18N
        jLabel8.setText("id");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 40, 20));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 110, -1));

        signup.setBackground(new java.awt.Color(51, 51, 51));
        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enter.png"))); // NOI18N
        signup.setText("sign up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/age.png"))); // NOI18N
        jLabel9.setText("dob");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 50, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));
        year.setToolTipText("");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/insert.jpg"))); // NOI18N
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 360));

        setSize(new java.awt.Dimension(678, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      //كود عدم تتكرار المدخلات
      private static Set<String> existingIDs = new HashSet<>();
    
    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed


     if(show.isSelected()){
         password.setEchoChar((char)0);
     }else{
         password.setEchoChar((char)'*');
     }

    }//GEN-LAST:event_showActionPerformed

    private void SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninActionPerformed
   login v = new login();
 v.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_SigninActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // فتح نافذة اختيار الملفات
                JFileChooser image = new JFileChooser();

                // تصفية الملفات لإظهار الصور فقط
                image.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg", "gif"));

                // عرض نافذة الاختيار الصوره
                int result = image.showOpenDialog(null);

                if (result == JFileChooser.APPROVE_OPTION) {
               //وضع الصوره المطلوبه
                    File selectedFile = image.getSelectedFile();
                    try {
                        // قراءة الصورة من الملف
                        BufferedImage image1 = ImageIO.read(selectedFile);
      // الحصول على أبعاد JLabel
   int labelWidth = Profile.getWidth();
          int labelHeight = Profile.getHeight();
                        // ضبط حجم الصورة لتناسب JLabel 
                        ImageIcon imageIcon = new ImageIcon(image1.getScaledInstance(labelWidth,labelHeight, Image.SCALE_SMOOTH));

                        // عرض الصورة في الـ JLabel
                        Profile.setIcon(imageIcon);

                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
      
    }//GEN-LAST:event_editActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
    user.setText("1990-01-01");
    }//GEN-LAST:event_userActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        try {
            
connection.con();
                 if(combo1.getSelectedIndex()==0){}
 
PreparedStatement st = connection.con().prepareStatement("insert into lap values(?,?,?,?,?)");
            
           
           st.setInt(1, Integer.parseInt(id.getText()));
            st.setString(2,user.getText());
            st.setString(3,password.getText());
               st.setString(4,email.getText());
            st.setString(5,phone.getText());
            st.setInt(1, Integer.parseInt(id.getText()));

            int y = st.executeUpdate();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(signup2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_signupActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // ما ينفع غير احولو استرينج
    //كود اخليه من ارقام معينه بدل ما اكتب كل رقم لواحدو عملت لوب
    
        for (int i = 1; i <= 31; i++) {
    day.addItem(Integer.toString(i)); }
        
for (int i = 1; i <= 12; i++) {
    month.addItem(Integer.toString(i)); }

for (int i = 2024; i >=1900; i--) {
    year.addItem(Integer.toString(i));}
    }//GEN-LAST:event_formWindowOpened

    private void ManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void ManItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ManItemStateChanged

        String gender = "Man";        
    }//GEN-LAST:event_ManItemStateChanged

    private void WomanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WomanItemStateChanged
        String gender = "Woman";  
    }//GEN-LAST:event_WomanItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Man;
    private javax.swing.JLabel Profile;
    private javax.swing.JButton Signin;
    private javax.swing.JRadioButton Woman;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JCheckBox show;
    private javax.swing.JButton signup;
    private javax.swing.JTextField user;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

    private boolean signup() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
